name: Dekko
favicon: null
layout_spectrum: 0.6451066699810326
typography_spectrum: 0.025730688590556383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.27689512190409005
  lightness: 0.5448125994298607
  saturation: 0.20403204998001456
  rhythmicContrast: 0.30564137105830014
purpose: []
